- hosts: localhost
  tasks:

  - name: Include main vars
    ansible.builtin.include_vars:
      file: vars.yml

  - name: Remove old versions of neovim
    ansible.builtin.file:
       path: "{{ home }}/neovim"
       state: absent

  - name: Clone neovim
    ansible.builtin.git:
       repo: https://github.com/neovim/neovim.git
       dest: "{{ home }}/neovim"
       depth: 1
       version: stable

  - name: "Install neovim deps"
    become: true
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - cmake
      - gettext
      - lua5.1
      - liblua5.1-0-dev

  - name: Clone Personal Repos
    ansible.builtin.git:
      repo: "https://github.com/theprimeagen/{{ repo }}.git"
      dest: "{{ personal }}/{{ repo }}"
      depth: 1
    vars:
      repos:
      - harpoon
      - vim-apm
      - vim-with-me
    loop_control:
      loop_var: repo
    with_items: "{{ repos }}"

  - name: Neovim Make Install
    become: true
    ansible.builtin.command: sudo make install
    args:
      chdir: "{{ home }}/neovim"

  - name: Rust... btw
    become: true
    ansible.builtin.shell:
      cmd: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

  - name: stylua
    ansible.builtin.shell:
      cmd: cargo install stylua

  - name: luarocks
    become: true
    ansible.builtin.shell:
      chdir: "{{ dev }}"
      cmd: ./resources/luarocks

  - name: luacheck
    become: true
    ansible.builtin.shell:
      cmd: luarocks install luacheck
